package gob.sunat.pojo;
// Generated 06-abr-2013 1:28:42 by Hibernate Tools 3.2.1.GA

import java.io.IOException;
import java.io.OutputStream;
import java.lang.annotation.Annotation;
import java.lang.reflect.Type;
import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.ws.rs.WebApplicationException;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.MultivaluedMap;
import javax.ws.rs.ext.MessageBodyWriter;
import javax.ws.rs.ext.Provider;





/**
 * Ruc generated by hbm2java
 */
@Provider
public class Ruc  implements MessageBodyWriter,java.io.Serializable {


     private Integer idRuc;
     private String ruc;
     private String nombre;
     private String dni;

    public Ruc() {
    }

    public Ruc(String ruc, String nombre, String dni) {
       this.ruc = ruc;
       this.nombre = nombre;
       this.dni = dni;
    }
   
   private static final long serialVersionUID = 1L;

    /**
     *
     * @return
     */
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id_ruc", precision=0)
    public Integer getIdRuc() {
        return this.idRuc;
    }
    
    public void setIdRuc(Integer idRuc) {
        this.idRuc = idRuc;
    }
    public String getRuc() {
        return this.ruc;
    }
    
    public void setRuc(String ruc) {
        this.ruc = ruc;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }

    @Override
    public boolean isWriteable(Class type, Type type1, Annotation[] antns, MediaType mt) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public long getSize(Object t, Class type, Type type1, Annotation[] antns, MediaType mt) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void writeTo(Object t, Class type, Type type1, Annotation[] antns, MediaType mt, MultivaluedMap mm, OutputStream out) throws IOException, WebApplicationException {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }


  @Override
    public String toString() {
        return "Ruc [idRuc=" + this.idRuc + ", ruc=" + this.ruc + "]";
    }
  
}


